# Generated by Django 2.2.13 on 2020-07-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcameras_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personobservation',
            name='observation_aggregate',
        ),
        migrations.RemoveField(
            model_name='personobservation',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='ObservationAggregate',
        ),
        migrations.DeleteModel(
            name='PersonObservation',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
