# Generated by Django 3.0.11 on 2020-11-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingress', '0004_auto_20201109_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingressqueue',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingress.Endpoint'),
        ),
    ]
