# Generated by Django 2.2.10 on 2020-03-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObservationAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_start", models.DateTimeField()),
                ("azimuth", models.IntegerField()),
                ("count", models.IntegerField()),
                ("cumulative_distance", models.FloatField()),
                ("cumulative_time", models.IntegerField()),
                ("median_speed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField()),
                ("sensor_code", models.CharField(max_length=255)),
                ("sensor_type", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("interval", models.IntegerField()),
                ("version", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=255, null=True)),
                ("supplier", models.CharField(max_length=255, null=True)),
                ("purpose", models.CharField(max_length=255, null=True)),
                ("area_gross", models.IntegerField(null=True)),
                ("area_net", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("length", models.IntegerField(null=True)),
                ("valid_from", models.DateTimeField(null=True)),
                ("valid_until", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonObservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.UUIDField()),
                ("observation_timestamp", models.DateTimeField()),
                ("distance", models.FloatField(null=True)),
                ("time", models.FloatField(null=True)),
                ("speed", models.FloatField(null=True)),
                ("type", models.CharField(max_length=255, null=True)),
                (
                    "observation_aggregate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telcameras_v2.ObservationAggregate",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telcameras_v2.Sensor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observationaggregate",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="telcameras_v2.Sensor"
            ),
        ),
    ]
