# Generated by Django 3.0.11 on 2021-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telcameras_v2', '0017_cmsa_15min_view_v7_again_20201201_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='countaggregate',
            name='count_in_scrambled',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='countaggregate',
            name='count_out_scrambled',
            field=models.SmallIntegerField(null=True),
        ),
    ]
