# Generated by Django 3.2.4 on 2021-08-10 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcameras_v2', '0032_deploy_v10_views_20210701_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggregate',
            name='distances',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
