# Generated by Django 3.2.8 on 2021-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telcameras_v2", "0033_alter_personaggregate_distances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaggregate",
            name="distances",
            field=models.JSONField(null=True),
        ),
    ]
