# Generated by Django 3.2.14 on 2022-09-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcameras_v2', '0034_alter_personaggregate_distances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countaggregate',
            old_name='area',
            new_name='area_size',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='sensor',
            new_name='sensor_name',
        ),
    ]
