# Generated by Django 3.2.14 on 2022-08-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0034_auto_20220830_1526'),
        ('telcameras_v2', '0034_alter_personaggregate_distances'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='area_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_v2_area_id', to='peoplemeasurement.area'),
        ),
        migrations.AddField(
            model_name='observation',
            name='line_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_v2_line_id', to='peoplemeasurement.line'),
        ),
        migrations.AddField(
            model_name='observation',
            name='sensor_gid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_v2_sensor_gid', to='peoplemeasurement.sensors'),
        ),
    ]
