# Generated by Django 3.0.6 on 2020-06-15 11:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dump', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
