# Generated by Django 2.2.13 on 2020-07-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcameras_vondelpark_tmp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsonDump',
        ),
    ]
