# Generated by Django 2.1.2 on 2018-11-01 08:05

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('versie', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('kenteken_land', models.CharField(max_length=2)),
                ('kenteken_nummer_betrouwbaarheid', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('kenteken_land_betrouwbaarheid', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('kenteken_karakters_betrouwbaarheid', django.contrib.postgres.fields.jsonb.JSONField()),
                ('indicatie_snelheid', models.FloatField()),
                ('automatisch_verwerkbaar', models.BooleanField()),
                ('voertuig_soort', models.CharField(max_length=25)),
                ('merk', models.CharField(max_length=255)),
                ('inrichting', models.CharField(max_length=255)),
                ('datum_eerste_toelating', models.DateField()),
                ('datum_tenaamstelling', models.DateField()),
                ('toegestane_maximum_massa_voertuig', models.SmallIntegerField()),
                ('europese_voertuig_categorie', models.CharField(max_length=2)),
                ('europese_voertuig_categorie_toevoeging', models.CharField(max_length=1)),
                ('tax_indicator', models.BooleanField()),
                ('maximale_constructie_snelheid_bromsnorfiets', models.SmallIntegerField()),
                ('brandstoffen', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
