# Generated by Django 2.1.5 on 2019-01-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0002_convert_passage_to_partition'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='versit_klasse',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
