# Generated by Django 2.1.5 on 2019-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0003_passage_versit_klasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='camera_kijkrichting',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='passage',
            name='europese_voertuigcategorie_toevoeging',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='voertuig_soort',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
