# Generated by Django 2.1.5 on 2019-01-22 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0005_auto_20190121_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='kenteken_land_betrouwbaarheid',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_nummer_betrouwbaarheid',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passage',
            name='straat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
