# Generated by Django 2.1.5 on 2019-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0006_auto_20190122_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='europese_voertuigcategorie',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='inrichting',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='merk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
