# Generated by Django 2.1.5 on 2019-02-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0007_auto_20190123_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='toegestane_maximum_massa_voertuig',
            field=models.IntegerField(null=True),
        ),
    ]
