# Generated by Django 3.0.11 on 2020-12-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("observation_timestamp", models.DateTimeField()),
                ("azimuth", models.SmallIntegerField()),
                ("count", models.SmallIntegerField()),
                ("cumulative_distance", models.FloatField()),
                ("cumulative_time", models.FloatField()),
                ("median_speed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message_id", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("sensor", models.CharField(max_length=255)),
                ("sensor_type", models.CharField(max_length=255)),
                ("sensor_state", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=13, max_digits=16)),
                ("longitude", models.DecimalField(decimal_places=13, max_digits=16)),
                ("interval", models.SmallIntegerField()),
                ("density", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("observation_timestamp", models.DateTimeField()),
                ("record", models.UUIDField()),
                ("distance", models.FloatField()),
                ("time", models.FloatField()),
                ("speed", models.FloatField()),
                ("person_observation_timestamp", models.DateTimeField()),
                ("type", models.CharField(max_length=255)),
                (
                    "group_aggregate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telcameras_v3.GroupAggregate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupaggregate",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="telcameras_v3.Observation",
            ),
        ),
    ]
