# Generated by Django 3.2.4 on 2021-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telcameras_v3", "0003_groupaggregate_count_scrambled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupaggregate",
            name="cumulative_distance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="groupaggregate",
            name="cumulative_time",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="groupaggregate",
            name="median_speed",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="density",
            field=models.FloatField(null=True),
        ),
    ]
