# Generated by Django 3.2.14 on 2022-09-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telcameras_v3', '0004_auto_20210603_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='sensor',
            new_name='sensor_name',
        ),
    ]
