# Generated by Django 2.2.10 on 2020-04-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0005_cmsa_15min_materialized_view_20200304_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementDetail',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=255)),
                ('count', models.FloatField()),
                ('peoplemeasurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peoplemeasurement.PeopleMeasurement')),
            ],
        ),
    ]
