# Generated by Django 3.0.11 on 2021-01-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('sensor', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('original_id', models.IntegerField()),
                ('admin_id', models.IntegerField()),
                ('area', models.FloatField(null=True)),
                ('density', models.FloatField(null=True)),
                ('total_distance', models.FloatField(null=True)),
                ('total_time', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CraCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimuth', models.FloatField(null=True)),
                ('count', models.IntegerField()),
                ('cra_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralerekenapplicatie_v1.CraModel')),
            ],
        ),
    ]
