# Generated by Django 3.0.11 on 2021-01-28 12:46

import contrib.timescale.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralerekenapplicatie_v1', '0002_to_timescale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areametric',
            name='total_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='areametric',
            name='total_time',
            field=models.FloatField(null=True),
        ),
    ]
