# Generated by Django 3.2.3 on 2021-05-26 14:21

from django.db import migrations, models

import contrib.timescale.fields


class Migration(migrations.Migration):
    dependencies = [
        ("centralerekenapplicatie_v1", "0003_auto_20210128_1346"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountMetric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message_id", models.TextField()),
                ("sensor", models.CharField(max_length=255)),
                (
                    "timestamp",
                    contrib.timescale.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("original_id", models.CharField(max_length=255)),
                ("admin_id", models.IntegerField()),
                ("count", models.IntegerField()),
                ("interval", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
