# Generated by Django 3.2.4 on 2021-06-16 13:08

import contrib.timescale.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralerekenapplicatie_v1', '0005_timescale_20210527_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areametric',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='areametric',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
