# Generated by Django 3.2.14 on 2022-08-30 11:57

import contrib.timescale.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralerekenapplicatie_v1', '0006_auto_20210616_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areametric',
            name='timestamp',
            field=contrib.timescale.fields.TimescaleDateTimeField(interval='1 day'),
        ),
        migrations.AlterField(
            model_name='countmetric',
            name='timestamp',
            field=contrib.timescale.fields.TimescaleDateTimeField(interval='1 day'),
        ),
        migrations.AlterField(
            model_name='linemetric',
            name='timestamp',
            field=contrib.timescale.fields.TimescaleDateTimeField(interval='1 day'),
        ),
        migrations.AlterField(
            model_name='linemetriccount',
            name='line_metric_timestamp',
            field=contrib.timescale.fields.TimescaleDateTimeField(interval='1 day'),
        ),
    ]
