# Generated by Django 2.2.16 on 2020-09-10 06:11

from django.db import migrations
from django.conf import settings


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create([
        Group(name=settings.GROUP_POST_DATA),
        Group(name=settings.GROUP_GET_DATA)
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(
        name__in=[
            settings.GROUP_POST_DATA,
            settings.GROUP_GET_DATA
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0013_servicelevel'),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
