# Generated by Django 3.0.11 on 2020-11-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplemeasurement", "0015_remove_sensors_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensors",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
