# Generated by Django 3.2.4 on 2021-07-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0021_auto_20210622_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='objectnummer',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
