# Generated by Django 3.2.4 on 2021-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplemeasurement", "0022_alter_sensors_objectnummer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensors",
            name="drop_incoming_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sensors",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
