# Generated by Django 3.2.7 on 2021-10-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0025_remove_sensors_drop_incoming_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='peoplemeasurement.sensors'),
        ),
        migrations.AlterField(
            model_name='line',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='peoplemeasurement.sensors'),
        ),
    ]
