# Generated by Django 3.2.7 on 2021-10-21 12:23

from django.db import migrations

from telcameras_v2.view_definitions import VIEW_STRINGS, get_view_strings


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0026_add_related_name_to_areas_and_lines_20211021_1135'),
        ('telcameras_v2', '0032_deploy_v10_views_20210701_1411'),
    ]

    _view_names = [
        "cmsa_15min_view_v7",
        "cmsa_15min_view_v8",
        "cmsa_15min_view_v9",
    ]

    operations = []

    for view_name in _view_names:
        operations.append(
            migrations.RunSQL(
                sql=f"DROP VIEW {view_name} CASCADE;",
            )
        )
