# Generated by Django 3.2.7 on 2021-10-21 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplemeasurement", "0027_drop_redundant_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VoorspelCoefficient",
        ),
        migrations.DeleteModel(
            name="VoorspelIntercept",
        ),
    ]
