# Generated by Django 3.2.9 on 2021-11-02 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoplemeasurement", "0028_alter_peoplemeasurement_details"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="area",
            unique_together={("sensor", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("sensor", "name")},
        ),
    ]
