# Generated by Django 3.2.12 on 2022-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0029_auto_20211102_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
