# Generated by Django 3.2.12 on 2022-07-13 16:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0030_auto_20220616_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='sensor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='peoplemeasurement.sensors'),
        ),
    ]
