# Generated by Django 3.2.12 on 2022-07-13 19:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoplemeasurement", "0031_auto_20220713_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="azimuth",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="line",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="line",
            name="sensor",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="peoplemeasurement.sensors",
            ),
        ),
    ]
