# Generated by Django 3.2.14 on 2022-09-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0032_auto_20220713_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='peoplemeasurement.sensors'),
        ),
        migrations.AlterField(
            model_name='line',
            name='azimuth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='peoplemeasurement.sensors'),
        ),
    ]
