# Generated by Django 3.2.14 on 2022-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0033_auto_20220825_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='line',
            name='line_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
