# Generated by Django 3.2.6 on 2021-10-20 09:52

import contrib.timescale.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cmsa15Min',
            fields=[
                ('bk_continuousaggregate_cmsa15min', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('sensor', models.CharField(max_length=255)),
                ('timestamp_rounded', contrib.timescale.fields.TimescaleDateTimeField(interval='1 day')),
                ('total_count', models.IntegerField(null=True)),
                ('count_down', models.IntegerField(null=True)),
                ('count_up', models.IntegerField(null=True)),
                ('density_avg', models.FloatField(null=True)),
                ('basedonxmessages', models.IntegerField(null=True)),
                ('total_count_p10', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('total_count_p20', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('total_count_p50', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('total_count_p80', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('total_count_p90', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_down_p10', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_down_p20', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_down_p50', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_down_p80', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_down_p90', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_up_p10', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_up_p20', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_up_p50', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_up_p80', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('count_up_p90', models.DecimalField(decimal_places=13, max_digits=16, null=True)),
                ('density_avg_p20', models.FloatField(null=True)),
                ('density_avg_p50', models.FloatField(null=True)),
                ('density_avg_p80', models.FloatField(null=True)),
                ('mf_insert_datetime', models.DateTimeField()),
                ('mf_update_datetime', models.DateTimeField(null=True)),
                ('mf_dp_available_datetime', models.DateTimeField()),
                ('mf_dp_changed_datetime', models.DateTimeField(null=True)),
                ('mf_row_hash', models.UUIDField(null=True)),
                ('mf_dp_latest_ind', models.BooleanField(null=True)),
                ('mf_deleted_ind', models.BooleanField(null=True)),
                ('mf_run_id', models.IntegerField(null=True)),
            ],
        ),
    ]
